# This file was generated by GoReleaser. DO NOT EDIT.
cask "htmlup" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "9d4f91202362e092f9c3a8f05d3766be3bbd8f0aa45ac0234f5f020c502291e7"
      url "https://github.com/truehhart/htmlup/releases/download/v#{version}/htmlup_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3a656f000ebd0de61ea6ddbe9f8432eda1a004539e6b5f8061bb852625131a5"
      url "https://github.com/truehhart/htmlup/releases/download/v#{version}/htmlup_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "511641b446a77305f8c051f0c383618678a108845d9d3f94aa88bff38f9e9379"
      url "https://github.com/truehhart/htmlup/releases/download/v#{version}/htmlup_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a5052e34404cae6accc701d6e0f5917d8d54753cc6264d0ad1d6dc911dbf11b"
      url "https://github.com/truehhart/htmlup/releases/download/v#{version}/htmlup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "htmlup"
  desc "Upload HTML pages and make them publicly available"
  homepage "https://github.com/truehhart/htmlup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "htmlup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/htmlup"]
    end
  end

  # No zap stanza required

end
