# This file was generated by GoReleaser. DO NOT EDIT.
cask "htmlup" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "f85fdf672e4c3486c94647d2f6b51b00386865833fdc5fd93e0451f84e043b6f"
      url "https://github.com/truehhart/htmlup/releases/download/v#{version}/htmlup_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d3dbc82d6a781e8efb814dbe3407fa290e0b99b888c04e2e3509bce2433433bd"
      url "https://github.com/truehhart/htmlup/releases/download/v#{version}/htmlup_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb2056fba4fc9b53f28cda44c67369a1d5d92fabc4fb8692230c43f80678d81b"
      url "https://github.com/truehhart/htmlup/releases/download/v#{version}/htmlup_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9309b50ec940cd02fdf8545ac4049f40f49cbc7d3ecf6bb3eab86122292d11e"
      url "https://github.com/truehhart/htmlup/releases/download/v#{version}/htmlup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "htmlup"
  desc "Upload HTML pages and make them publicly available"
  homepage "https://github.com/truehhart/htmlup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "htmlup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/htmlup"]
    end
  end

  # No zap stanza required

end
