# This file is generated by the slowed-and-reverb publish workflow. DO NOT EDIT.
cask "slowed-and-reverb" do
  version "0.1.2"
  sha256 "86da318821e27ff79574ed65c63e57cb9f416264c20533b3bd5b2d2c2c761665"

  url "https://github.com/truehhart/slowed-and-reverb/releases/download/v0.1.2/Slowed.and.Reverb_0.1.2_aarch64.dmg"
  name "Slowed and Reverb"
  desc "Play YouTube audio slowed and reverbed"
  homepage "https://github.com/truehhart/slowed-and-reverb"

  depends_on arch: :arm64

  app "Slowed and Reverb.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Slowed and Reverb.app"]
  end
end
