# This file is generated by the slowed-and-reverb publish workflow. DO NOT EDIT.
cask "slowed-and-reverb" do
  version "0.1.1"
  sha256 "4ca06f6fcd5240d6d9681e1cfb0322b8bcb1bb4843844955f371ee9b1ee21436"

  url "https://github.com/truehhart/slowed-and-reverb/releases/download/v0.1.1/Slowed and Reverb_0.1.1_aarch64.dmg"
  name "Slowed and Reverb"
  desc "Play YouTube audio slowed and reverbed"
  homepage "https://github.com/truehhart/slowed-and-reverb"

  depends_on arch: :arm64

  app "Slowed and Reverb.app"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Slowed and Reverb.app"]
  end
end
